spring:
  application:
    name: batch

  profiles:
    active: local

  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/batch-db;MODE=MySQL
      username: sa
      password:

  batch:
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.batch: INFO
    com.example.batch: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch-exam
    username: postgres
    password: postgres

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.batch: INFO
    com.example.batch: DEBUG