spring:
  application:
    name: batch

  profiles:
    active: local

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/batch-db;MODE=MySQL
      username: sa
      password:

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.batch: INFO
    com.example.batch: DEBUG